### PR TITLE
added title in feed discovery as per document

### PR DESCRIPTION
**Pull request by rajjanorkar**
added title in feed discovery as per document 
https://docs.zendframework.com/zend-feed/find-feeds/

### CODE REVIEW

**Comment by froschdesign** [comment]
@rajjanorkar 
If you create a new feature or find a bug, please add always an unit test. Thanks!

Btw. good catch!

**Comment by rajjanorkar** [comment]
Hi @froschdesign 
I am really not that good in writing test, and for this scenario i tried but not getting idea.

I improved it to used nodeValue than title attribute not all links have title.

edit : nodeValue does not make sense here as we are only searching for link tag so we have title attribute for that tag.

I have added test created another pull request. (i am just editing here on github so was not able to combine both in one pull request (pull request 64)

Thank you

**Comment by froschdesign** [comment]
@rajjanorkar 
Add the unit test here.

**Comment by rajjanorkar** [comment]
@froschdesign added

**Comment by rajjanorkar** [comment]
@froschdesign could you please merge ?

**Comment by froschdesign** [comment]
@rajjanorkar 
The workflow is not completed: a review is still needed.

**Comment by rajjanorkar** [comment]
I think the process is so slow here...

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Welcome to OSS 😑

**Comment by rajjanorkar** [comment]
Thanks @Ocramius

**Comment by weierophinney** [comment]
Thanks, @rajjanorkar

**Pull request merged**
