### PR TITLE
Added getImage function for Atom feed entry

### PR DESCRIPTION
**Pull request by rajjanorkar**

### CODE REVIEW

**Comment by rajjanorkar** [comment]
I am not sure why checks are failing, can anyone please help.

**Comment by lowtower** [comment]
Hello @rajjanorkar,
You added a method but provided no test for it.
So, the coverage decreased, which makes coveralls fail.
Travis build passed successfully.
Cheers,
LT.

**Comment by rajjanorkar** [comment]
ok cool, thanks @lowtower

**Comment by weierophinney** [comment]
Closing, per my [comment on #57](https://github.com/zendframework/zend-feed/pull/57#issuecomment-388970926).

**Pull request closed without merging**
