### PR TITLE
fix warning 'Parameter must be an array or an object that implements …

### PR DESCRIPTION
**Pull request by remicollet**
…Countable' (PHP 7.2)

Discovered in Fedora QA
https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-feed?collection=f28

### CODE REVIEW

**Comment by remicollet** [comment]
I use the `if ($result && ...) `as this bolean test already used in `setSubscription`

Test suite only raise this warning in `hasSubscription` method, other check only added for consistency, so  for sanity

**Comment by michalbundyra** [comment]
@remicollet All changes I can see are:
```diff
 -        if (count($result)) {
 +        if ($result && count($result)) {
```

Wouldn't be enough to have just:
```php
if ($result) {
```
?

**Comment by remicollet** [comment]
@webimpress no idea, I don't now enough the whole stack involved here, so I just copy/paste a previously used test.

**Comment by michalbundyra** [comment]
@remicollet it seems we need both, because it is an object, not a 'normal' array... :)

**Comment by weierophinney** [comment]
Thanks, @remicollet

**Pull request merged**
