### PR TITLE
Fixed the enclosure length check to allow zero as recommended by the …

### PR DESCRIPTION
**Pull request by EreMaijala**
…RSS Advisory Board (http://www.rssboard.org/rss-profile#element-channel-item-enclosure) and removed an extraneous isset() check.

### CODE REVIEW

**Comment by EreMaijala** [comment]
Ping? I'd really appreciate any response on this PR.

**Comment by GeeH** [comment]
Hi @EreMaijala - please make sure you've written/updated corresponding tests for this fix.

**Comment by EreMaijala** [comment]
There are already tests for non-numeric length and negative length. I didn't add new ones since there were no existing tests for other success cases, e.g. positive length, either. I'll add those now.

**Comment by EreMaijala** [comment]
Done. I added checks for zero and positive length. There's also an additional test to verify that a positive number string still works as it did before this patch.

**Pull request closed without merging**
